var gnudex = [
{
        name:'MissingNo.',
        type:['Normal','Flying'],
        imune:['ghost'],
        hp:33,
        attack:136,
        defense:0,
        special:6,
        speed:29,
        hplvl:1.66,
        attacklvl:.56,
        defenselvl:.56,
        speciallvl:1.24,
        speedlvl:.56
},
{name:"Bulbasaur", type:["Grass","Poison"]},
{name:"Ivysaur", type:["Grass","Poison"]},
{name:"Venusaur", type:["Grass","Poison"]},
{name:"Charmander", type:["Fire"]},
{name:"Charmeleon", type:["Fire"]},
{name:"Charizard", type:["Fire","Flying"]},
{name:"Squirtle", type:["Water"]},
{name:"Wartortle", type:["Water"]},
{name:"Blastoise", type:["Water"]},
{name:"Caterpie", type:["Bug"]},
{name:"Metapod", type:["Bug"]},
{name:"Butterfree", type:["Bug","Flying"]},
{name:"Weedle", type:["Bug","Poison"]},
{name:"Kakuna", type:["Bug","Poison"]},
{name:"Beedrill", type:["Bug","Poison"]},
{name:"Pidgey", type:["Normal","Flying"]},
{name:"Pidgeotto", type:["Normal","Flying"]},
{name:"Pidgeot", type:["Normal","Flying"]},
{name:"Rattata", type:["Normal"]},
{name:"Raticate", type:["Normal"]},
{name:"Spearow", type:["Flying"]},
{name:"Fearow", type:["Normal","Flying"]},
{name:"Ekans", type:["Poison"]},
{name:"Arbok", type:["Poison"]},
{name:"Pikachu", type:["Electric"]},
{name:"Raichu", type:["Electric"]},
{name:"Sandshrew", type:["Ground"]},
{name:"Sandslash", type:["Ground"]},
{name:"Nidoran Female", type:["Poison"]},
{name:"Nidorina", type:["Poison"]},
{name:"Nidoqueen", type:["Poison","Ground"]},
{name:"Nidoran Male", type:["Poison"]},
{name:"Nidorino", type:["Poison"]},
{name:"Nidoking", type:["Poison","Ground"]},
{name:"Clefairy", type:["Normal"]},
{name:"Clefable", type:["Normal"]},
{name:"Vulpix", type:["Fire"]},
{name:"Ninetales", type:["Fire"]},
{name:"Jigglypuff", type:["Normal"]},
{name:"Wigglytuff", type:["Normal"]},
{name:"Zubat", type:["Poison","Flying"]},
{name:"Golbat", type:["Poison","Flying"]},
{name:"Oddish", type:["Grass","Poison"]},
{name:"Gloom", type:["Grass","Poison"]},
{name:"Vileplume", type:["Grass","Poison"]},
{name:"Paras", type:["Bug","Grass"]},
{name:"Parasect", type:["Bug","Grass"]},
{name:"Venonat", type:["Bug","Poison"]},
{name:"Venomoth", type:["Bug","Poison"]},
{name:"Diglett", type:["Ground"]},
{name:"Dugtrio", type:["Ground"]},
{name:"Meowth", type:["Normal"]},
{name:"Persian", type:["Normal"]},
{name:"Psyduck", type:["Water"]},
{name:"Golduck", type:["Water"]},
{name:"Mankey", type:["Fighting"]},
{name:"Primeape", type:["Fighting"]},
{name:"Growlithe", type:["Fire"]},
{name:"Arcanine", type:["Fire"]},
{name:"Poliwag", type:["Water"]},
{name:"Poliwhirl", type:["Water"]},
{name:"Poliwrath", type:["Water","Fighting"]},
{name:"Abra", type:["Psychic"]},
{name:"Kadabra", type:["Psychic"]},
{name:"Alakazam", type:["Psychic"]},
{name:"Machop", type:["Fighting"]},
{name:"Machoke", type:["Fighting"]},
{name:"Machamp", type:["Fighting"]},
{name:"Bellsprout", type:["Grass","Poison"]},
{name:"Weepinbell", type:["Grass","Poison"]},
{name:"Victreebel", type:["Grass","Poison"]},
{name:"Tentacool", type:["Water","Poison"]},
{name:"Tentacruel", type:["Water","Poison"]},
{name:"Geodude", type:["Rock","Ground"]},
{name:"Graveler", type:["Rock","Ground"]},
{name:"Golem", type:["Rock","Ground"]},
{name:"Ponyta", type:["Fire"]},
{name:"Rapidash", type:["Fire"]},
{name:"Slowpoke", type:["Water","Psychic"]},
{name:"Slowbro", type:["Water","Psychic"]},
{name:"Magnemite", type:["Electric"]},
{name:"Magneton", type:["Electric"]},
{name:"Farfetch'd", type:["Normal","Flying"]},
{name:"Doduo", type:["Normal","Flying"]},
{name:"Dodrio", type:["Normal","Flying"]},
{name:"Seel", type:["Water"]},
{name:"Dewgong", type:["Water","Ice"]},
{name:"Grimer", type:["Poison"]},
{name:"Muk", type:["Poison"]},
{name:"Shellder", type:["Water"]},
{name:"Cloyster", type:["Water","Ice"]},
{name:"Gastly", type:["Ghost","Poison"]},
{name:"Haunter", type:["Ghost","Poison"]},
{name:"Gengar", type:["Ghost","Poison"]},
{name:"Onix", type:["Rock","Ground"]},
{name:"Drowzee", type:["Psychic"]},
{name:"Hypno", type:["Psychic"]},
{name:"Krabby", type:["Water"]},
{name:"Kingler", type:["Water"]},
{name:"Voltorb", type:["Electric"]},
{name:"Electrode", type:["Electric"]},
{name:"Exeggcute", type:["Grass","Psychic"]},
{name:"Exeggutor", type:["Grass","Psychic"]},
{name:"Cubone", type:["Ground"]},
{name:"Marowak", type:["Ground"]},
{name:"Hitmonlee", type:["Fighting"]},
{name:"Hitmonchan", type:["Fighting"]},
{name:"Lickitung", type:["Normal"]},
{name:"Koffing", type:["Poison"]},
{name:"Weezing", type:["Poison"]},
{name:"Rhyhorn", type:["Ground","Rock"]},
{name:"Rhydon", type:["Ground","Rock"]},
{name:"Chansey", type:["Normal"]},
{name:"Tangela", type:["Grass"]},
{name:"Kangaskhan", type:["Normal"]},
{name:"Horsea", type:["Water"]},
{name:"Seadra", type:["Water"]},
{name:"Goldeen", type:["Water"]},
{name:"Seaking", type:["Water"]},
{name:"Staryu", type:["Water"]},
{name:"Starmie", type:["Water","Psychic"]},
{name:"Mr. Mime", type:["Psychic"]},
{name:"Scyther", type:["Bug","Flying"]},
{name:"Jynx", type:["Ice","Psychic"]},
{name:"Electabuzz", type:["Electric"]},
{name:"Magmar", type:["Fire"]},
{name:"Pinsir", type:["Bug"]},
{name:"Tauros", type:["Normal"]},
{name:"Magikarp", type:["Water"]},
{name:"Gyarados", type:["Water","Flying"]},
{name:"Lapras", type:["Water","Ice"]},
{name:"Ditto", type:["Normal"]},
{name:"Eevee", type:["Normal"]},
{name:"Vaporeon", type:["Water"]},
{name:"Jolteon", type:["Electric"]},
{name:"Flareon", type:["Fire"]},
{name:"Porygon", type:["Normal"]},
{name:"Omanyte", type:["Rock","Water"]},
{name:"Omastar", type:["Rock","Water"]},
{name:"Kabuto", type:["Rock","Water"]},
{name:"Kabutops", type:["Rock","Water"]},
{name:"Aerodactyl", type:["Rock","Flying"]},
{name:"Snorlax", type:["Normal"]},
{name:"Articuno", type:["Ice","Flying"]},
{name:"Zapdos", type:["Electric","Flying"]},
{name:"Moltres", type:["Fire","Flying"]},
{name:"Dratini", type:["Dragon"]},
{name:"Dragonair", type:["Dragon"]},
{name:"Dragonite", type:["Dragon","Flying"]},
{name:"Mewtwo", type:["Psychic"]},
{name:"Mew", type:["Psychic"]},
{name:"Chikorita  ", type:["Grass"]},
{name:"Bayleef", type:["Grass"]},
{name:"Meganium", type:["Grass"]},
{name:"Cyndaquil", type:["Fire"]},
{name:"Quilava", type:["Fire"]},
{name:"Typhlosion", type:["Fire"]},
{name:"Totodile", type:["Water"]},
{name:"Croconaw", type:["Water"]},
{name:"Feraligatr", type:["Water"]},
{name:"Sentret  *fan*", type:["Normal"]},
{name:"Furret", type:["Normal"]},
{name:"HootHoot   *pic*", type:["Normal","Flying"]},
{name:"Noctowl", type:["Normal","Flying"]},
{name:"Ledyba", type:["Bug","Flying"]},
{name:"Ledian", type:["Bug","Flying"]},
{name:"Spinarak", type:["Bug","Poison"]},
{name:"Ariados", type:["Bug","Poison"]},
{name:"Crobat", type:["Flying","Poison"]},
{name:"Chinchou", type:["Electric","Water"]},
{name:"Lanturn", type:["Electric","Water"]},
{name:"Pichu   *pic*", type:["Electric"]},
{name:"Cleffa", type:["Normal"]},
{name:"Igglybuff   *fanart*", type:["Normal"]},
{name:"Togepi", type:["Normal"]},
{name:"Togetic", type:["Normal","Flying"]},
{name:"Natu", type:["Psychic","Flying"]},
{name:"Xatu", type:["Psychic","Flying"]},
{name:"Mareep", type:["Electric"]},
{name:"Flaaffy", type:["Electric"]},
{name:"Ampharos", type:["Electric"]},
{name:"Bellossom", type:["Grass"]},
{name:"Marill   *pic*", type:["Water"]},
{name:"Azumarill", type:["Water"]},
{name:"Sudowoodo   *fan*", type:["Rock"]},
{name:"Politoed", type:["Water"]},
{name:"Hoppip", type:["Grass","Flying"]},
{name:"Skiploom", type:["Grass","Flying"]},
{name:"Jumpluff", type:["Grass","Flying"]},
{name:"Aipom", type:["Normal"]},
{name:"Sunkern", type:["Grass"]},
{name:"Sunflora", type:["Grass"]},
{name:"Yanma", type:["Bug","Flying"]},
{name:"Wooper", type:["Water","Ground"]},
{name:"Quagsire", type:["Water","Ground"]},
{name:"Espeon", type:["Psychic"]},
{name:"Umbreon   ", type:["Dark"]},
{name:"Murkrow", type:["Dark","Flying"]},
{name:"Slowking    *pic*", type:["Psychic","Water"]},
{name:"Misdreavus    *fan*", type:["Ghost"]},
{name:"Unown", type:["Psychic"]},
{name:"Woobuffet", type:["Psychic"]},
{name:"Girafarig", type:["Psychic","Normal"]},
{name:"Pineco", type:["Bug"]},
{name:"Foretress", type:["Steel","Bug"]},
{name:"Dunsparce    *fan*", type:["Normal"]},
{name:"Gligar", type:["Flying","Ground"]},
{name:"Steelix", type:["Steel","Ground"]},
{name:"Snubbull", type:["Normal"]},
{name:"Granbull", type:["Normal"]},
{name:"Quilfish", type:["Water","Poison"]},
{name:"Scizor ", type:["Bug","Steel"]},
{name:"Schuckle", type:["Bug","Rock"]},
{name:"Heracross", type:["Bug","Fighting"]},
{name:"Sneazle   *fan*", type:["Dark","Ice"]},
{name:"Teddiursa", type:["Normal"]},
{name:"Ursaring", type:["Normal"]},
{name:"Slugma", type:["Fire"]},
{name:"Magcargo", type:["Fire","Rock"]},
{name:"Swinub", type:["Ice","Ground"]},
{name:"Piloswine", type:["Ice","Ground"]},
{name:"Corsola", type:["Water","Rock"]},
{name:"Remoraid", type:["Water"]},
{name:"Octillery", type:["Water"]},
{name:"Delibird", type:["Ice","Flying"]},
{name:"Mantine", type:["Water","Flying"]},
{name:"Skarmony", type:["Steel","Flying"]},
{name:"Houndour", type:["Dark","Fire"]},
{name:"Houndoom", type:["Dark","Fire"]},
{name:"Kingdra", type:["Water","Dragon"]},
{name:"Phanpy", type:["Ground"]},
{name:"Donaphan", type:["Ground"]},
{name:"Porygon2", type:["Normal"]},
{name:"Stantler", type:["Normal"]},
{name:"Smeargle   *fan*", type:["Normal"]},
{name:"Tyrogue", type:["Fighting"]},
{name:"Hitmontop", type:["Fighting"]},
{name:"Smoochum", type:["Ice","Psychic"]},
{name:"Elekid", type:["Electric"]},
{name:"Magby", type:["Fire"]},
{name:"Miltank", type:["Normal"]},
{name:"Blissey", type:["Normal"]},
{name:"Raikou", type:["Electric"]},
{name:"Entei", type:["Fire"]},
{name:"Suicune   *fan*", type:["Water"]},
{name:"Larvitar", type:["Rock","Ground"]},
{name:"Pupitar", type:["Rock","Ground"]},
{name:"Tyranitar", type:["Rock","Dark"]},
{name:"Lugia   *pic*", type:["Flying","Psychic"]},
{name:"Ho-Oh", type:["Flying","Fire"]},
{name:"Celebi", type:["Grass","Psychic"]},
{name:"Treecko", type:["Grass"]},
{name:"Grovyle ", type:["Grass"]},
{name:"Sceptile", type:["Grass"]},
{name:"Torchic", type:["Fire"]},
{name:"Combusken", type:["Fire","Fighting"]},
{name:"Blaziken", type:["Fire","Fighting"]},
{name:"Mudkip", type:["Water","Ground"]},
{name:"Marshtomp", type:["Water","Ground"]},
{name:"Swampert", type:["Water","Ground"]},
{name:"Poochyena", type:["Dark"]},
{name:"Mightyena", type:["Dark"]},
{name:"Zigzagoon", type:["Dark"]},
{name:"Linoone", type:["Normal"]},
{name:"Wurmple", type:["Bug"]},
{name:"Silcoon", type:["Bug"]},
{name:"Beautifly", type:["Bug","Flying"]},
{name:"Cascoon", type:["Bug"]},
{name:"Dustox", type:["Bug","Poison"]},
{name:"Lotad", type:["Water","Grass"]},
{name:"Lombre", type:["Water","Grass"]},
{name:"Ludicolo", type:["Water","Grass"]},
{name:"Seedot", type:["Grass"]},
{name:"Nuzleaf", type:["Grass","Dark"]},
{name:"Shiftry", type:["Grass","Dark"]},
{name:"Taillow", type:["Normal","Flying"]},
{name:"Sellow", type:["Normal","Flying"]},
{name:"Wingull", type:["Water","Flying"]},
{name:"Pelipper", type:["Water","Flying"]},
{name:"Ralts", type:["Psychic"]},
{name:"Kirlia", type:["Psychic"]},
{name:"Gardevoir", type:["Psychic"]},
{name:"Surskit", type:["Water","Bug"]},
{name:"Masquerain", type:["Flying","Bug"]},
{name:"Shroomish", type:["Grass"]},
{name:"Breloom", type:["Grass","Fighting"]},
{name:"Slakoth", type:["Normal"]},
{name:"Vigoroth", type:["Normal"]},
{name:"Slaking", type:["Normal"]},
{name:"Nincada", type:["Bug","Ground"]},
{name:"Ninjask", type:["Bug","Flying"]},
{name:"Shedinja", type:["Bug","Ghost"]},
{name:"Whismur", type:["Normal"]},
{name:"Loudred", type:["Normal"]},
{name:"Exploud", type:["Normal"]},
{name:"Makuhita", type:["Fighting"]},
{name:"Hariyama", type:["Fighting"]},
{name:"Azurill", type:["Normal"]},
{name:"Nosepass", type:["Rock"]},
{name:"Skitty", type:["Normal"]},
{name:"Delcatty", type:["Normal"]},
{name:"Sapleye", type:["Dark","Ghost"]},
{name:"Mawile", type:["Steel"]},
{name:"Aron", type:["Steel","Rock"]},
{name:"Lairon", type:["Steel","Rock"]},
{name:"Aggron", type:["Steel","Rock"]},
{name:"Meditite", type:["Fighting","Psychic"]},
{name:"Medicham", type:["Fighting","Psychic"]},
{name:"Electrike", type:["Electric"]},
{name:"Manectric", type:["Electric"]},
{name:"Plusle", type:["Electric"]},
{name:"Minun", type:["Electric"]},
{name:"Volbeat", type:["Bug"]},
{name:"Illumise", type:["Bug"]},
{name:"Roselia", type:["Grass","Poison"]},
{name:"Gulpin", type:["Poison"]},
{name:"Swalot", type:["Poison"]},
{name:"Carvanha", type:["Water","Dark"]},
{name:"Sharpedo", type:["Water","Dark"]},
{name:"Wailmer", type:["Water"]},
{name:"Wailord", type:["Water"]},
{name:"Numel", type:["Water"]},
{name:"Camerupt", type:["Fire","Ground"]},
{name:"Torkoal", type:["Fire"]},
{name:"Spoink", type:["Psychic"]},
{name:"Grumpig", type:["Psychic"]},
{name:"Spinda", type:["Normal"]},
{name:"Trapinch", type:["Ground"]},
{name:"Vibrava", type:["Ground","Dragon"]},
{name:"Flygon", type:["Ground","Dragon"]},
{name:"Cacnea", type:["Grass"]},
{name:"Cacturne", type:["Grass","Dark"]},
{name:"Swablu", type:["Normal","Flying"]},
{name:"Altaria", type:["Dragon","Flying"]},
{name:"Zangoose", type:["Normal"]},
{name:"Seviper", type:["Poison"]},
{name:"Lunatone", type:["Rock","Psychic"]},
{name:"Solrock", type:["Rock","Psychic"]},
{name:"Barboach", type:["Ground","Water"]},
{name:"Whiscash", type:["Ground","Water"]},
{name:"Corphish", type:["Water"]},
{name:"Crawdaunt", type:["Water","Dark"]},
{name:"Baltoy", type:["Psychic","Ground"]},
{name:"Claydol", type:["Psychic","Ground"]},
{name:"Lileep", type:["Rock","Grass"]},
{name:"Cradily", type:["Rock","Grass"]},
{name:"Anorith", type:["Rock","Bug"]},
{name:"Amaldo", type:["Rock","Bug"]},
{name:"Feebas", type:["Water"]},
{name:"Milotic", type:["Water"]},
{name:"Castform", type:["Normal"]},
{name:"Kecleon", type:["Normal"]},
{name:"Shuppet", type:["Ghost"]},
{name:"Banette", type:["Ghost"]},
{name:"Duskull", type:["Ghost"]},
{name:"Dusclops", type:["Ghost"]},
{name:"Tropius", type:["Flying","Grass"]},
{name:"Chimecho", type:["Psychic"]},
{name:"Absol", type:["Dark"]},
{name:"Wynaut", type:["Psychic"]},
{name:"Snorunt", type:["Ice"]},
{name:"Glalie", type:["Ice"]},
{name:"Spheal", type:["Ice","Water"]},
{name:"Sealeo", type:["Ice","Water"]},
{name:"Walrein", type:["Ice","Water"]},
{name:"Clamperl", type:["Water"]},
{name:"Huntail", type:["Water"]},
{name:"Gorebyss", type:["Water"]},
{name:"Relicanth", type:["Water","Rock"]},
{name:"Luvdisc", type:["Water"]},
{name:"Bagon", type:["Dragon"]},
{name:"Shelgon", type:["Dragon"]},
{name:"Salamence", type:["Dragon","Flying"]},
{name:"Beldum", type:["Steel","Psychic"]},
{name:"Metang", type:["Steel","Psychic"]},
{name:"Metagross", type:["Steel","Psychic"]},
{name:"Regirock", type:["Rock"]},
{name:"Regice", type:["Ice"]},
{name:"Registeel", type:["Steel"]},
{name:"Latias", type:["Psychic","Dragon"]},
{name:"Latios", type:["Psychic","Dragon"]},
{name:"Kyogre", type:["Water"]},
{name:"Groundon", type:["Ground"]},
{name:"Rayquaza", type:["Dragon","Flying"]},
{name:"Jirachi", type:["Steel","Psychic"]},
{name:"Deoxys", type:["Psychic"]}
]

var gnutype = {
Bug:{
  Good:['Grass','Psychic', 'Dark'],
  Bad: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel']},
Dark :{
  Good:['Ghost','Psychic'],
  Bad:['Fighting','Dark Steel']},
Dragon :{
  Good:[' Dragon'],
  Bad:[' Ice','Steel']},
Electric :{
  Good:['Water','Flying'],
  Bad:['Grass','Electric','Ground','Dragon']},
Fighting :{
  Good:['Normal','Ice','Rock','Dark','Steel'],
  Bad:['Poison','Flying','Bug','Ghost ','Psychic']},
Fire :{
  Good:['Grass','Ice','Bug','Steel'],
  Bad:['Water','Fire','Dragon','Rock']},
Flying :{
  Good:['Grass','Fighting','Bug'],
  Bad:['Electric','Rock','Steel']},
Ghost :{
  Good:['Ghost','Psychic'],
  Bad:['Dark','Steel']},
Grass :{
  Good:['Water','Ground','Rock'],
  Bad:['Fire','Grass','Poison','Flying','Bug','Dragon','Steel']},
Ground :{
  Good:['Fire','Poison','Electric','Rock','Steel'],
  Bad:['Grass','Flying','Bug']},
Ice :{
  Good:['Grass','Ground','Flying','Dragon'],
  Bad:['Water','Ice','Fire','Steel']},
Normal :{
  Good:[],
  Bad:[' Fighting','Ghost','Rock','Steel']},
Poison :{
  Good:['Grass'],
  Bad:['Poison','Ground','Rock','Ghost','Steel']},
Psychic :{
  Good:['Fighting','Poison'],
  Bad:['Psychic','Dark','Steel']},
Rock :{
  Good:['Ice','Fire','Flying','Bug'],
  Bad:['Fighting','Ground','Steel']},
Steel :{
  Good:['Ice','Rock'],
  Bad:['Water','Fire','Water','Steel']},
Water :{
  Good:[' Fire','Ground','Rock'],
  Bad:[' Water','Grass','Dragon']}
}


for(i=0;i<=386;i++){
  j=i//Math.ceil(Math.random()*150)
  name=gnudex[j].name
  type=gnudex[j].type
  type1=type[0]
  type2=type[1]
  good1 = gnutype[type1].Good
  bad1 = gnutype[type1].Bad
  if(undefined!=type2){
    good2 = gnutype[type2].Good
    bad2 = gnutype[type2].Bad
  }
  message='Number '+j+', '+name+' is '+type1
  if(undefined!=type2)
    message += ' and '+type2
  message += "\n"+type1+' is good against '+good1+' but bad against '+bad1+"\n"
  if(undefined!=type2)
    message += type2+' is good against '+good2+' but bad against '+bad2+"\n"
  console.log(message)
}

